### ISSUE TITLE
Event Handler for MessageReceived(int id, string msg) 

### ISSUE THREAD

**Issue by Xerotherm1c** [Cloet/SimpleSockets#25]
Hola, first and foremost thank you very much for contributing this codebase to the open-source community. It saved me a lot of frustration right off the bat. However, I'm now running into a issue that I believe is a bug unless I'm misunderstanding the `id` parameter of the `MessageReceived` event handler.

**To Reproduce**

1. Open a Server Listener
2. Open multiple client connections to the given Listener
3. Set a break point on the `internal void InvokeMessageReceived(int id, string text)` function (called when `(State.Header == "MESSAGE")` evaluates as true)
4. Have client 1 send multiple messages using `SendMessage()` to the server

The first message has an id of 1 as expected, but the second message has an id of 2. My understanding is that the id value passed should indicate which client id sent the message. If I've misunderstood the id parameter, please explain the proper use of it, and could you also explain how I might determine which client id sent the message to the Server Listener? Again I was thinking it would be the `Id` value inside the passed `State`.

Likewise, the `MessageReceived` event does not seem to be firing for additional clients. Only the first client seems to raise this event, despite it being attached to the Listener. I believe this is a bug but it's possible that I've modified something and that it may not be reproducible on your end. Please let me know what you are able to find.

Thanks for your time!

**Comment by Cloet** [comment]
I'm having a bit of trouble replicating this issue. You need to set the events for each client you're declaring so that might be the issue? Could you send me a snippet of your code so I could determine what is going wrong?

**Comment by Xerotherm1c** [comment]
I have set the events using a `BindEvents()` function similar to in the examples provided in the repository (by the way perhaps we should update the readme to include a proper example `BindEvents()` function? Took me a bit of digging to get to). I am passing the Listener by reference which the examples did not, but this should not cause any issue, should it?

```
public void BindEvents(ref ServerListener listener) {

    listener.ProgressFileTransfer += Progress;
    listener.MessageReceived += MessageReceived;
    listener.MessageSubmitted += MessageSubmitted;
    listener.CustomHeaderReceived += CustomHeaderReceived;
    listener.ClientDisconnected += ClientDisconnected;
    listener.ClientConnected += ClientConnected;
    listener.FileReceived += FileReceived;
    listener.ServerHasStarted += ServerHasStarted;
    listener.MessageFailed += MessageFailed;
    listener.ServerErrorThrown += ErrorThrown;

    Application.ApplicationExit += new EventHandler(this.OnApplicationExit);

}
```

And my `MessageReceived()` function hooked up to the Listener's `MessageReceived` event works great for the first client, but does not seem to get triggered by the second client.

```
private void MessageReceived(int id, string msg) { // Client #2's messages are not raising this event / firing this function.

   Console.WriteLine("[MsgReceived(" + id + ")] Contents: " + msg); // The ID printing here alternates between 1 & 2 even when both messages were transmitted by Client Connection w/ ID=1.

    /// ...

}
```

**Comment by Cloet** [comment]
Your listener events are correct. The ID Parameter corresponds to the int of the Dictionary that stores all the connected clients. So maybe your client disconnects and reconnects ? I've yet to implement a unique identifier per socket, for now the first connected client = 1, second = 2 and so on.
`
// Returns all currently connected clients
public IDictionary<int, ISocketInfo> GetConnectedClients()
{
     return ConnectedClients.ToDictionary(x => x.Key, x => (ISocketInfo) x.Value);
}
`

**Comment by Xerotherm1c** [comment]
My clients are not disconnecting but the second client will not raise the event for `MessageReceived`. Or, if they are disconnecting, `ClientDisconnectedInvoke` never fires. I was able to also determine that the connections are unstable when a second client connects, and the original `MessageReceived` event will often stop firing entirely. Could the the event bindings be getting set when the first client connects, but destroyed at some point when a new client connects? Any ideas for continuing this troubleshooting would be much appreciated, 'cause I'm pretty close to out of ideas.

**Comment by Cloet** [comment]
There might be an issue with your events, it could be a bug too. I’ve actually rewritten this library check https://github.com/Cloet/AsyncClientServer/tree/SimpleSockets?files=1 it doesn’t implement SSL yet but it should work I just tested it with 500 clients yesterday, also it gives a guid to each client. That way you can check if it’s the same client or not.

**Comment by Xerotherm1c** [comment]
I appreciate the link to the other project but the reason I went with your library was for the SSL implementation. Nonetheless, I will refer to it regarding the guid logic and see what I can come up with. Thanks!

**Comment by Cloet** [comment]
I’ve actually just added SSL to that project!

**Comment by Xerotherm1c** [comment]
Oh, perfect! I'll see what I can come up with when I can dig into the other project. Thanks again, and great work :)

**Comment by Cloet** [comment]
No not yet, tomorrow I'll probably rewrite the readme, list all the changes and add a lot of new info. I'm also doing a bit of testing with ssl at the moment but it should already work fine.

**Comment by Xerotherm1c** [comment]
Well I've discovered that I needed to add a byref parameter to my `BindEvents()` method based on how I'm creating my `SocketClient`s. I'm able to get data from both clients now with the correct clientId as discussed previously (for testing I've made each client send distinctly identifiable messages to the server), but I've discovered some strange behavior. I can send maybe 10 to 15 messages from client 1, but then no more messages will trigger the `MessageReceived` event of the server - until and unless I start sending messages from client 2 to the server. Then I'll get the server's `MessageReceived` event to trigger another 10 or so times, and the messages that are printed to my log file are almost perfectly alternating between client 1's message and client 2's messages. Any idea why this might happen?

Also, I was previously using `SendMessage()` instead of `SendMessageAsync()`, though I've now switched to using the async method. Still encountering the alternating received messages.

**Comment by Cloet** [comment]
It seems like the Ssl listener has some issues receiving messages, I’ve fixed the majority, I’m still working on Ssl receiving.

**Comment by Cloet** [comment]
I know where my mistake is but I just haven’t had time yet. The issue is when i’m sending a lot of messages at once (test is 10k messages from 500 clients) i’ll receive 4.8m messages instead of 5m. Smaller test works fine though.

When i’m done fixing this i’ll update the Readme (it needs a lot of work) i’ll add a parameter for the timer.
