### ISSUE TITLE
Events not triggered

### ISSUE THREAD

**Issue by NaolShow** [Cloet/SimpleSockets#27]
**Describe the bug**
Events do not trigger

**To Reproduce**
1. Create a project with framework 4.7.2
2. Create a SimpleSocketTcpClient
3. Bind events (AuthFailed / AuthSuccess for exemple) and send console writeline to test
4. Start the client
5. Events do not trigger

**Expected behavior**
Events being triggered

**Desktop**
 - OS: Windows 10
- .NET 4.7.2 framework

**Additional context**
I tried 4 events (AuthFailed / AuthSuccess) & (ServerConnected & ServerDisconnected)
Only ServerConnected is working.
When my server is down and trying to connect to it with AuthFailed event nothing is triggered.

Thanks for your help! I love your library (I was looking for one which is simple to use) Thanks :)

**My code:**
`
        public` MainWindow() {
            InitializeComponent();

            Start();

        }

        private void Start() {

            // Initialization
            SimpleSocketClient client = new SimpleSocketTcpClient();

            // Events
            client.AuthFailed += ClientOnAuthFailed;
            client.AuthSuccess += ClientOnAuthSuccess;

            // Start
            Console.WriteLine("Connecting...");
            client.StartClient("127.0.0.1", 1000);

        }

        private void ClientOnAuthFailed() {
            Console.WriteLine("Failed to authenticate.");
        }

        private void ClientOnAuthSuccess() {
            Console.WriteLine("Authenticated with success.");
        }
`

**Comment by Cloet** [comment]
Authfailed and authsucces is only teiggered when using Ssl, you should use the clientconnected and clientdisconnected

**Comment by NaolShow** [comment]
Thanks for your answer. But I do not have any ClientConnect / ClientDisconnect event with SimpleSocketTcpClient...

**Comment by Cloet** [comment]
Sorry my bad! Those are the server events, client is : ConnectedToServer and DisconnectedFromServer

**Comment by NaolShow** [comment]
Ok thanks, for me DisconnectFromServer is triggered only when I close the client.
So I made a little code that just wait for the client to connect. And if he's not connected after 3 tries = 9 seconds, I just close the client.

`public MainWindow() {
            InitializeComponent();

            Start();

        }

        private void Start() {

            // Initialization
            SimpleSocketTcpClient client = new SimpleSocketTcpClient();

            // Bind events
            BindEvents(client);

            // Connect
            client.StartClient("127.0.0.1", 19726, 3);

            Task.Run(() => {

                // Wait for the client to connect
                int tries = 0;
                while (true) {

                    // Wait
                    Thread.Sleep(100);
                    // If client is connected, break
                    if (client.IsConnected() || tries == 30) {
                        break;
                    }
                    tries++;

                }

                // Not connected
                if (tries == 30) {

                    Console.WriteLine("Client is not connected..");
                    client.Close();

                }

            });

        }

        private void BindEvents(SimpleSocketClient client) {

            client.ConnectedToServer += (socket) => {
                Console.WriteLine("Connected!");

                client.SendMessage("Hello server!");
            };
            client.DisconnectedFromServer += (socket) => {
                Console.WriteLine("Disconnected!");
            };

        }`

I don't know if it's the best way to do this but thanks :) !

**Comment by NaolShow** [comment]
Better way to do it: 

`private void WaitClientState(SimpleSocketClient client, int maxTries, Action onFailConnect, Action onSuccessConnect) {

            Task.Run(() => {

                // Wait client to connect, or tries to reach max tries
                for (int i = 0; i != maxTries * 10; i++) {

                    // Wait
                    Thread.Sleep(100);
                    // If client is connected, break
                    if (client.IsConnected()) {
                        onSuccessConnect?.Invoke();
                        return;
                    }

                }
                onFailConnect?.Invoke();

            });

        }

        private void Start() {

            // Initialization
            SimpleSocketTcpClient client = new SimpleSocketTcpClient();

            // Connect
            client.StartClient("127.0.0.1", 19726, 3);

            // Wait client state
            WaitClientState(client, 3, delegate {

                Console.WriteLine("Client is not connected..");
                client.Close();

            }, delegate {

                Console.WriteLine("Client is connected!");

            });

        }`
