### ISSUE TITLE
SendMessageAsync 

### ISSUE THREAD

**Issue by mturetchi** [Cloet/SimpleSockets#28]
Hi, I have a question.

On client Part:
When I try to set "close parameter" of SendMessageAsync method, to true.
Is thrown this exception:
Exception thrown: 'System.ObjectDisposedException' in System.dll ("Cannot access a disposed object.") | System.ObjectDisposedException

This behavior isn't implemented?
How to fix it?
Thanks.

**Comment by Cloet** [comment]
The close parameter indicates that the object will be disposed, so after closing a socket it cannot be reused. You have to make a new instance of the socket.

**Comment by mturetchi** [comment]
OK, I understand, thank you.

**Comment by mturetchi** [comment]
I tried to create a new instance of the socket, it's working, I used your code from the examples.
But the exception is thrown anyway.
![image](https://user-images.githubusercontent.com/40790150/67658071-381bca00-f961-11e9-86eb-ad1e87db13ea.png)

![image](https://user-images.githubusercontent.com/40790150/67658085-423dc880-f961-11e9-945c-8207c9e1cada.png)
