### ISSUE TITLE
Server communication stops after client reconnect using ssl

### ISSUE THREAD

**Issue by ABlueCasket** [Cloet/SimpleSockets#30]
**Description**
If SimpleSockets is used with SSL encryption first everything looks perfect. After clients disconnect and reconnect (restart client app) the server notices that client connected to server. Server also authenticate the client. From that moment on server ignores everything what client trys to send.

**To Reproduce**
1. Edit Examples
1a. Server.cs -> comment line 31 and uncomment line 32 ; insert a valid certificate
Line looks like `_listener = new SimpleSocketTcpSslListener(@"c:\wrk\a\srv2.pfx","test");`
1b. Client.cs --> comment line 30 and uncomment line 31; insert a valid certificate
Line looks like: `_client = new SimpleSocketTcpSslClient(@"c:\wrk\b\srv2.pfx", "test");`

2. Start Server
3. Start Client
4. Send Message from client (press M -> type message)
5. Server receive message

6. Stop Client App
7. Start Client App

Server confirms client again: 
> Server authenticate certificate of client 1 .
> Client 1 with IPv4  has connected to the server.

8. Send Message from client (press M -> type message)
9. Server does nothing...

**Expected behavior**
Server acts like on the first connection of client

**Screenshots**
not applicable

**Desktop (please complete the following information):**
 - Testet with MS Win 10 Pro and Ubuntu Linux 18.04 with Mono
 - Testet Nugget Version 1.0.1 and latest github source (November 25, 2019)

**Comment by Cloet** [comment]
Thanks for the detailed info, just searched  a bit for the issue. The SSL server was not handling multiple clients correctly. Latest master should fix this.
