### ISSUE TITLE
Overload SimpleSocketTcpSsl Constructor to provide Certificate directly

### ISSUE THREAD

**Issue by ABlueCasket** [Cloet/SimpleSockets#32]
In a current project I need to provide the certificate content from string. Writing the certificate content into a file and load it again is just bugy...

So I would be very happy if a SimpleSocketTcpSsl Constructor provides the possibility to do that. Providing an X509Certificate2 Object to Constructor would be imho just as good as providing the content as sting.

**Comment by Cloet** [comment]
Yeah sure I'll add that, the code just reads the file and converts it to a X509Certificate2 object anyway.

**Comment by Cloet** [comment]
Feature has been added to the master.

**Comment by ABlueCasket** [comment]
perfect! thanks a lot!
