### ISSUE TITLE
System.OverflowException: Arithmetic operation resulted in an overflow.

### ISSUE THREAD

**Issue by developervariety** [Cloet/SimpleSockets#33]
**Describe the bug**
I'm using TPL to send data back and forth as fast as possible with a 3 second wait time after 5 packets are sent. An exception is thrown within the first 30 seconds of running the program.

**To Reproduce**

Client side:
```csharp
more:
 Parallel.For(0, 5, new ParallelOptions {
  MaxDegreeOfParallelism = 1
 }, async i => {
  packet = new Packet {
   command = "cmd",
    id = Guid.NewGuid(),

    meta = new List < object > {
     "data"
    }
  };

  await SocketClient.SendMessageAsync(JsonSerializer.Serialize(packet));
 });

await Task.Delay(TimeSpan.FromSeconds(3));
goto more;

Server side:
Look at my other comment, send something similar.
```

**Expected behavior**
Communication to flow freely with no exceptions.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Perhaps instead of using Int32 we could move onto Int64?

```csharp
[12: 22: 31 FTL] Unhandled exception thrown on socket client
Unhandled exception.System.Exception: Object reference not set to an instance of an object.
 -- - > System.NullReferenceException: Object reference not set to an instance of an object.
at SimpleSockets.Client.SimpleSocketTcpSslClient.Receive(IClientMetadata state, Int32 offset)
 -- - End of inner exception stack trace-- -
 at SimpleSockets.Client.SimpleSocketTcpSslClient.Receive(IClientMetadata state, Int32 offset)
at SimpleSockets.Client.SimpleSocketTcpSslClient.ReceiveCallback(IAsyncResult result)
at System.Threading.Tasks.Task. < > c. < ThrowAsync > b__139_1(Object state)
at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
System.OverflowException: Arithmetic operation resulted in an overflow.
at SimpleSockets.Messaging.SimpleMessage.ReadData(Int32 receive)
at SimpleSockets.Messaging.SimpleMessage.ReadBytesAndBuildMessage(Int32 receive)
at SimpleSockets.Client.SimpleSocketTcpSslClient.ReceiveCallback(IAsyncResult result)```

**Comment by developervariety** [comment]
I should mention that messages being sent from the remote server are large. This exception occurs on the client (receiving) side. I have implemented `MessagePack` serialization to reduce the size, but I'm still crashing (client side).

**Comment by Cloet** [comment]
It’s possible if your messages are large the Int32 isn’t big enough, I’ll take a look at it tomorrow.

**Comment by developervariety** [comment]
Here is a JSON serialized message of a "large" message.

```json
{"command":"cmd","id":"a3d50b8e-2c58-4bb4-967e-7af2a1a9b8f9","request":{"uri":"test","headers":[{"name":"Accept","value":"*/*"},{"name":"Accept-Encoding","value":"gzip, deflate"},{"name":"Accept-Language","value":"en-US"},{"name":"Connection","value":"keep-alive"},{"name":"Content-Type","value":"application/x-www-form-urlencoded; charset=UTF-8"},{"name":"Origin","value":"https://www.test.com"},{"name":"Referer","value":"https://www.test.com/"},{"name":"User-Agent","value":"user-agent"}],"parameters":[{"name":"bda","value":"W3sidmFsdWUiOiJqcyIsImtleSI6ImFwaV90eXBlIn0seyJrZXkiOiJwIiwidmFsdWUiOjF9LHsia2V5IjoiZiIsInZhbHVlIjoiYTc3OWY5OTAxMWQ3YmEzMmM4Zjk3MGNkMTYzOWEyYTIifSx7ImtleSI6Im4iLCJ2YWx1ZSI6Ik1UVTNOemd4TmpRd053PT0ifSx7ImtleSI6IndoIiwidmFsdWUiOiJmNDc5ODZmMmVkZTVlYjRlN2Q3MmE2YmFiYTc5NTA1ZXwyMjUwMjc1ZjE1M2JhMzQwMGEzYjBlOTkzMTllZjRlNyJ9LHsidmFsdWUiOlsiRE5UOjIiLCJMOmVuLVVTIiwiRDoyNCIsIlBSOjIiLCJTOjE2MDAsOTAwIiwiQVM6MTYwMCw4NzMiLCJUTzoyNDAiLCJTUzp0cnVlIiwiTFM6dHJ1ZSIsIklEQjp0cnVlIiwiQjpmYWxzZSIsIk9EQjpmYWxzZSIsIkNQVUM6dW5rbm93biIsIlBLOldpbjMyIiwiQ0ZQOi0xNTI5NzY4MDUiLCJGUjpmYWxzZSIsIkZPUzpmYWxzZSIsIkZCOmZhbHNlIiwiSlNGOkFyaWFsLENvdXJpZXIsQ291cmllciBOZXcsR2VvcmdpYSxIZWx2ZXRpY2EsTW9uYWNvLFBhbGF0aW5vLFRhaG9tYSxUaW1lcyxUaW1lcyBOZXcgUm9tYW4sVmVyZGFuYSIsIlA6Q2hyb21pdW0gUERGIFBsdWdpbixDaHJvbWl1bSBQREYgVmlld2VyLE5ld3MgZmVlZCBoYW5kbGVyIiwiVDowLHRydWUsdHJ1ZSIsIkg6MyIsIlNXRjp0cnVlIl0sImtleSI6ImZlIn0seyJrZXkiOiJjcyIsInZhbHVlIjoxfSx7ImtleSI6ImpzYmQiLCJ2YWx1ZSI6IntcdTAwMjJITFx1MDAyMjoyLFx1MDAyMk5DRVx1MDAyMjp0cnVlLFx1MDAyMkRBXHUwMDIyOm51bGwsXHUwMDIyRFJcdTAwMjI6bnVsbCxcdTAwMjJETVRcdTAwMjI6NDcsXHUwMDIyRE9cdTAwMjI6bnVsbCxcdTAwMjJET1RcdTAwMjI6MTB9In1d"},{"name":"public_key","value":"public_key"},{"name":"site","value":"https://www.test.com"},{"name":"userbrowser","value":"user-agent"},{"name":"simulate_rate_limit","value":0},{"name":"simulated","value":0},{"name":"language","value":"en"},{"name":"rnd","value":0.6168009227219974}]},"meta":[true]}
```

**Comment by Cloet** [comment]
That message doesn’t seem large enough to give an issue about int32 size so it’s probanly something else, i’ll try to replicate it tomorrow

**Comment by developervariety** [comment]
This bug seems like an issue with how fast TPL is sending packets to the remote server, and the response just overwhelms the client side buffer.

**Comment by Cloet** [comment]
I've found the problem, the messagereceiving part uses recursion so if a lot of messages are received this can create a stackoverflow issue. The weird part is it only seems to happen with the Ssl socket, i'll fix it asap.

**Comment by Cloet** [comment]
The issue is fixed and pushed to master but i'm still running some tests to check if stackoverflowexception can still occur

**Comment by developervariety** [comment]
Thanks for the push, I still have yet to test it on my side, but this fix also work for objects received?

**Comment by Cloet** [comment]
It should fix all types of messages!

**Comment by Cloet** [comment]
I’ll do some more testing tonight.

**Comment by Cloet** [comment]
I've let the socket constantly send messages like your given JSON text for about 3 hours and no errors were shown. Nuget and master are now up to date and fixed.

**Comment by developervariety** [comment]
Alright so it seems to not crash anymore due to the buffer on client side, but this library have some sort of DoS protection?

I'm sending 5 packets with TPL with a 1 second wait-time and the server socket throws an exception.

```csharp
[23:06:22 FTL] [Application]: Unhandled exception thrown by socket.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.get_Available()
   at SimpleSockets.Server.SimpleSocketListener.IsConnected(Int32 id)
```

Client side appears to be disconnected (expected behavior since server crashed). Could these two issues correlate or are there no sockets usable due to the speed?

**Comment by developervariety** [comment]
```csharp
[23:22:25 FTL] [Remote Server]: Unhandled exception was thrown by socket.
System.OverflowException: Arithmetic operation resulted in an overflow.
   at SimpleSockets.Messaging.SimpleMessage.ReadData(Int32 receive)
   at SimpleSockets.Messaging.SimpleMessage.ReadBytesAndBuildMessage(Int32 receive)
   at SimpleSockets.Client.SimpleSocketTcpSslClient.ReceiveCallback(IAsyncResult result)
Unhandled exception. [Unhandled exception. Unhandled exception. 23:22:28Unhandled exception.  FTL] [Application]: Unhandled exception throw by solver/module.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at SimpleSockets.SimpleSocket.CompressBytesAsync(Byte[] plainBytes)
   at SimpleSockets.Messaging.SimpleMessage.CompressEncryptHeaderAsync()
   at SimpleSockets.Messaging.SimpleMessage.BuildAsync()
   at SimpleSockets.Client.SimpleSocketClient.SendObjectAsync(Object obj, Boolean compress, Boolean encrypt, Boolean close)
   at Client.Util.Network.CommandHelper.Request(String requestCode, List`1 meta) in D:\rcs\Client\Util\Network\CommandHelper.cs:line 40
   at Client.Core.Engine.InitiateTask() in D:\rcs\Client\Core\Engine.cs:line 31
```

**Comment by Cloet** [comment]
Are you closing/disposing the socket after each message ?

**Comment by developervariety** [comment]
Nope. Do you have some sort of communication method I could use so I can send you my project files? I rather not upload them publicly.

**Comment by Cloet** [comment]
You can dm me on Twitter (@MathiasCloet) or reddit (Cloetzz) or something else if you have any suggestions?

**Comment by Cloet** [comment]
or just email me mathias.cloet@hotmail.com

**Comment by ABlueCasket** [comment]
In my project I have a similar issue with large messages using MessageContracts. if the object i trying to send getting lager, the client throws an ObjectDisposedException

**Comment by developervariety** [comment]
@ABlueCasket same issue occurs with me. The client side disconnects from the server randomly when the buffer gets overwhelmed.

@Cloet I ended up implementing a slower approach so the client/server don't crash.

**Comment by Cloet** [comment]
Does this occur at the start of the program or after the program is running a bit longer ?

**Comment by Cloet** [comment]
I'm going to upgrade the int32 to UInt64 and check what the other possible causes could be.

**Comment by ABlueCasket** [comment]
In my case, the Error only occur, if Message length is lager then something about 16k

> 03.01.2020 16:58:41 [Debug] - [ListenerLOG:  ]Message has been built and has a length of 15658

this worked
if Message is a bit larger it crashes if client send to server.
vice versa the MessageContracts receive Event is not fired and nothing happens...

**Comment by developervariety** [comment]
Alright so this is the way my setup works.

The remote server is online, and the client connects. After connecting, the client sends a packet for license validity and the remote server responds with an answer. The client then sends 5 packets within a TPL loop requesting a Http Request body. At this point within a few seconds of receiving a few messages it crashes due to `Arithmetic operation` or sometimes there isn't an exception at all and the server crashes saying there is no client connected.

I have my setup this way to prevent RE'ing of my application. Mostly all functions/requests are on the remote server and without a valid license you cannot use the program.

**Comment by Cloet** [comment]
I did find a bug that could causes issues when sending larger messages/objects. That issue is now fixed, but I'm not sure if that fixes the Arithmetic Exception because I was unable to replicate that error. Unless you're sending messages larger then 2Gb?

**Comment by ABlueCasket** [comment]
Hi,
i just testet your current version and all my problems are gone!
just great! thank you so very much for your great work and your really fast Troubleshooting!!

**Comment by developervariety** [comment]
I am unable to test this build just yet, but if it works for @ABlueCasket then it should work for me.

@Cloet, You could perhaps use TPL and see if the Arithmetic operation exception pops up. This is all a speed issue really bc the server is sending so many packets at once and the buffer is overwhelming itself and crashes (my setup at least).
