### ISSUE TITLE
[Feature Request] Disconnect Idle Clients

### ISSUE THREAD

**Issue by developervariety** [Cloet/SimpleSockets#35]
**Is your feature request related to a problem? Please describe.**
Implement a feature to disconnect idle clients in `SimpleSocketListener` base class.

**Describe the solution you'd like**
Disconnect idle clients in X seconds

**Describe alternatives you've considered**
Packets that update a dictionary of the last time the keep-alive packet was sent (my own keep-alive packet)

**Additional context**
N/A

**Comment by Cloet** [comment]
I'll take a look at when I have time, probably this weekend or something.

**Comment by Cloet** [comment]
I've been quite busy with school so it has taken me a while, but the feature has been added to the master branch. I'll do some more test tomorrow and release it to nuget etc.
