### ISSUE TITLE
BeginRead-Method Exception using SSL

### ISSUE THREAD

**Issue by ABlueCasket** [Cloet/SimpleSockets#39]
**Describe the bug**
Today I tested your new nuget version 1.1.6 (old Version was 1.1.5 from git clone). I changed nothing on source code but  there is thrown an Exception

> 31.01.2020 17:38:18 [Error] - Die BeginRead-Methode kann nicht aufgerufen werden, wenn ein anderer read-Vorgang ansteht.
> 
> 31.01.2020 17:38:18 [Debug] - Die BeginRead-Methode kann nicht aufgerufen werden, wenn ein anderer read-Vorgang ansteht.
> 
>    bei System.Net.Security._SslStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
>    bei System.Net.Security._SslStream.BeginRead(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback asyncCallback, Object asyncState)
>    bei System.Net.Security.SslStream.BeginRead(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback asyncCallback, Object asyncState)
>    bei SimpleSockets.Server.SimpleSocketTcpSslListener.Receive(IClientMetadata state, Int32 offset)
> 31.01.2020 17:38:18 [Error] - Server Error: Die BeginRead-Methode kann nicht aufgerufen werden, wenn ein anderer read-Vorgang ansteht.
> 
> 31.01.2020 17:38:18 [Warn ] - Stack Trace follows:
>    bei System.Net.Security._SslStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
>    bei System.Net.Security._SslStream.BeginRead(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback asyncCallback, Object asyncState)
>    bei System.Net.Security.SslStream.BeginRead(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback asyncCallback, Object asyncState)
>    bei SimpleSockets.Server.SimpleSocketTcpSslListener.Receive(IClientMetadata state, Int32 offset)
> 31.01.2020 17:38:18 [Info ] - Client ID 1 getrennt: Remote-IP 127.0.0.1 auf Remote-System
> 31.01.2020 17:38:18 [Debug] - Client ID 1 mit Remote-IP 127.0.0.1 auf Remote-System  was removed from client list
> 31.01.2020 17:38:18 [Debug] - [ListenerLOG:  ]Closing socket from client with id:1 and Guid:

**To Reproduce**
SSL 

**Expected behavior**
should work as 1.1.5 

**Screenshots**
not applicable

**Comment by Cloet** [comment]
I’ll take a look at it and add some tests to the workflow this weekend so things like this won’t happen again.

**Comment by Cloet** [comment]
The problem has been solved, a new version has been released and should be validated by nuget any moment.

**Comment by ABlueCasket** [comment]
Hi,
i tested out version 1.1.65 from nugget and ist seems to work like expected.
thanks a lot again!
