### ISSUE TITLE
MessageContract Messages disappear without trace using SSL and mono

### ISSUE THREAD

**Issue by ABlueCasket** [Cloet/SimpleSockets#44]
I started a lot of tests today using the given examples to avoid other influences. I placed the server on a cloud server. The client is my local computer. Using SSL there is no MessageContract received. If I switch to SimpleSocketTcpClient everything works fine. 

It seems there occures a problem when using MessageContracts if the server runs with mono.
If there is anything I can do to help debugging, please tell me!

**Comment by ABlueCasket** [comment]
It was pretty much my fault...
I rebuilded the whole solution and published it as .netCore Application and everything works as it should...
Sorry for stealing your precious time reading this and thinking about...

**Comment by Cloet** [comment]
I’m glad you’ve found the problem! I haven’t had a lot of time to look more into it because I was quite bust with school! But I love helping with problems, it helps create better software.
